##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [2.26.0] date: [Sat Mar 17 16:58:20 MSK 2018]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = main

######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og -Wall


#######################################
# paths
#######################################
# source path

# firmware library path
PERIFLIB_PATH = 

# Build path
BUILD_DIR = build

######################################
# source
######################################

# C sources
C_SOURCES =  \
main.c \
SSD1331.c \
tim2_delay.c 

TARGET_STDPERIPH_SRC_PATH = stm_lib/src
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/misc.c
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_adc.c
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_bkp.c
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_crc.c
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_dma.c
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_exti.c
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_flash.c
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_gpio.c
#C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_i2c.c
#C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_iwdg.c
#C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_pwr.c
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_rcc.c
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_rtc.c
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_spi.c
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_tim.c
C_SOURCES += $(TARGET_STDPERIPH_SRC_PATH)/stm32f10x_usart.c
C_SOURCES += cmsis_boot/system_stm32f10x.c
#C_SOURCES += cmsis_boot/startup/startup_stm32f10x_md.c

# ASM sources
#ASM_SOURCES =  \
#src/startup.S
#startup_stm32f103xb.s


######################################
# firmware library
######################################
PERIFLIB_SOURCES = 


#######################################
# binaries
#######################################
BINPATH=/usr/bin
PREFIX=arm-none-eabi-
CC = $(BINPATH)/$(PREFIX)gcc
AS = $(BINPATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(BINPATH)/$(PREFIX)objcopy
AR = $(BINPATH)/$(PREFIX)ar
SZ = $(BINPATH)/$(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
#AS_DEFS = 

# C defines
C_DEFS =  \
-DSTM32F10X_MD
#-DUSE_HAL_DRIVER \
#-DSTM32F103xB
#-DSSD1306_USE_I2C \
#-DSTM32F1 # for ssd1306 library


# AS includes
#AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-Istm_lib/inc \
-Icmsis \
-Icmsis_boot
#-I$(FIRMWARE)/Drivers/STM32F1xx_HAL_Driver/Inc \
#-I$(FIRMWARE)/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy \
#-I$(FIRMWARE)/Drivers/CMSIS/Device/ST/STM32F1xx/Include \
#-I$(FIRMWARE)/Drivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = ld/stm32_rom.ld

# libraries
LIBS = -lc -lm -lnosys
LIBDIR =
LDFLAGS =  -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) ./src/startup.o
	$(CC) -mcpu=cortex-m3 -mthumb -Wl,$(LDFLAGS),-o$(BUILD_DIR)/$(TARGET).elf,-Map,$(TARGET).map ./src/startup.o $(OBJECTS)
	#$(CC) -mcpu=cortex-m3 -mthumb -Wl,$(LDFLAGS),-o$(TARGET).elf,-Map,$(TARGET).map ./build/startup_stm32f10x_md.o $(OBJECTS)
	$(SZ) $@

%.o: %.S
	@echo "  CC $<"
	@$(CC) $(INCLUDE) $(CFLAGS)  $< -o $*.o

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR .dep $(BUILD_DIR)

flash: all
	st-flash --reset write build/$(TARGET).bin 0x8000000
erase:
	st-flash --reset erase
uart:
	screen /dev/ttyACM0

#######################################
# dependencies
#######################################
-include $(shell mkdir .dep 2>/dev/null) $(wildcard .dep/*)

# *** EOF ***
